### ISSUE TITLE
Filed to connect to mongodb

### ISSUE THREAD

**Issue by zhouhao27** [icflorescu/openshift-cartridge-mongodb#22]
By following [this repository](https://github.com/antt001/parse-server-example), I create an application in openshift.

<img width="803" alt="2016-10-04 9 48 38" src="https://cloud.githubusercontent.com/assets/8099731/19078183/dffbb2b4-8a81-11e6-91c8-143ba134555a.png">

I click the url, the parse page loaded successfully. But when I tried to access dashboard, the page never stop loading...

And when I check the log, it shows:

```
parse-server-example running on port 8080.
info: Parse LiveQuery Server starts running
warn: Unable to ensure uniqueness for usernames:  MongoError: failed to connect to server [localhost:43016] on first connect
    at Pool.<anonymous> (/var/lib/openshift/57f3a8d22d5271067700004b/app-root/runtime/repo/node_modules/mongodb-core/lib/topologies/server.js:313:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/var/lib/openshift/57f3a8d22d5271067700004b/app-root/runtime/repo/node_modules/mongodb-core/lib/connection/pool.js:260:12)
    at Connection.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/var/lib/openshift/57f3a8d22d5271067700004b/app-root/runtime/repo/node_modules/mongodb-core/lib/connection/connection.js:162:49)
    at Socket.g (events.js:291:16)
    at emitOne (events.js:96:13)
warn: Unable to ensure uniqueness for user email addresses:  MongoError: failed to connect to server [localhost:43016] on first connect
    at Pool.<anonymous> (/var/lib/openshift/57f3a8d22d5271067700004b/app-root/runtime/repo/node_modules/mongodb-core/lib/topologies/server.js:313:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/var/lib/openshift/57f3a8d22d5271067700004b/app-root/runtime/repo/node_modules/mongodb-core/lib/connection/pool.js:260:12)
    at Connection.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/var/lib/openshift/57f3a8d22d5271067700004b/app-root/runtime/repo/node_modules/mongodb-core/lib/connection/connection.js:162:49)
    at Socket.g (events.js:291:16)
    at emitOne (events.js:96:13)
(node:470919) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): MongoError: failed to connect to server [localhost:43016] on first connect
(node:470919) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): MongoError: failed to connect to server [localhost:43016] on first connect
```

I got the port number by:

`rhc port-forward -a {myapp}`

It seems I need the username and password for mongodb. I'd like to create in my db. Then when I ssh to my mongodb gear. I enter `mongo`, then got:

> bash: mongo: command not found

What should I do? Thanks

**Comment by zhouhao27** [comment]
I think it has nothing to do with the username and password. The real problem is:

> failed to connect to server [127.0.0.1:40121] on first connect' } MongoError

What could be the reason cause this?  And how should I debug this problem? Thanks.

Or should I use 127.0.0.1? Because my gear of mongodb is different from the nodejs.

**Comment by zhouhao27** [comment]
Solved the problem by recreate the application. But this time I tried this one instead of use your nodejs cartridge. 

And I'm using my own parse-server app instead of the one from the github.

<img width="575" alt="2016-10-05 11 35 21" src="https://cloud.githubusercontent.com/assets/8099731/19101605/352d9c82-8afc-11e6-9971-a9083545e9d6.png">
